//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Acc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Acc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Models.Acc", typeof(Acc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DeptCatId {
            get {
                return ResourceManager.GetString("DeptCatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, and one number..
        /// </summary>
        public static string PasswordRegularExpression {
            get {
                return ResourceManager.GetString("PasswordRegularExpression", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Role_Admin {
            get {
                return ResourceManager.GetString("Role_Admin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string Role_HR {
            get {
                return ResourceManager.GetString("Role_HR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Super Admin / HR.
        /// </summary>
        public static string Role_SuperAdmin {
            get {
                return ResourceManager.GetString("Role_SuperAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Area Manager.
        /// </summary>
        public static string Role_AreaManager {
            get {
                return ResourceManager.GetString("Role_AreaManager", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Store Manager.
        /// </summary>
        public static string Role_StoreManager {
            get {
                return ResourceManager.GetString("Role_StoreManager", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shift Leader.
        /// </summary>
        public static string Role_ShiftLeader {
            get {
                return ResourceManager.GetString("Role_ShiftLeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sales Staff.
        /// </summary>
        public static string Role_SalesStaff {
            get {
                return ResourceManager.GetString("Role_SalesStaff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Part-time Staff.
        /// </summary>
        public static string Role_PartTimeStaff {
            get {
                return ResourceManager.GetString("Role_PartTimeStaff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username or email to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        public static string PhoneNumber {
            get { return ResourceManager.GetString("PhoneNumber", resourceCulture); }
        }
        public static string DateOfBirth {
            get { return ResourceManager.GetString("DateOfBirth", resourceCulture); }
        }
        public static string Gender {
            get { return ResourceManager.GetString("Gender", resourceCulture); }
        }
        public static string Gender_Male {
            get { return ResourceManager.GetString("Gender_Male", resourceCulture); }
        }
        public static string Gender_Female {
            get { return ResourceManager.GetString("Gender_Female", resourceCulture); }
        }
        public static string Gender_Other {
            get { return ResourceManager.GetString("Gender_Other", resourceCulture); }
        }
        public static string Avatar {
            get { return ResourceManager.GetString("Avatar", resourceCulture); }
        }
    }
}