//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Models {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Employee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Employee() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Models.Employee", typeof(Employee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string EmployeeAcc {
            get {
                return ResourceManager.GetString("EmployeeAcc", resourceCulture);
            }
        }
        
        public static string EmployeeFullName {
            get {
                return ResourceManager.GetString("EmployeeFullName", resourceCulture);
            }
        }
        
        public static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        public static string EmployeeRole {
            get {
                return ResourceManager.GetString("EmployeeRole", resourceCulture);
            }
        }
        
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        public static string StoreId_RangeError {
            get {
                return ResourceManager.GetString("StoreId_RangeError", resourceCulture);
            }
        }

        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }

        public static string EmploymentType {
            get {
                return ResourceManager.GetString("EmploymentType", resourceCulture);
            }
        }

        public static string EmploymentType_FullTime {
            get {
                return ResourceManager.GetString("EmploymentType_FullTime", resourceCulture);
            }
        }

        public static string EmploymentType_PartTime {
            get {
                return ResourceManager.GetString("EmploymentType_PartTime", resourceCulture);
            }
        }

        public static string EmploymentType_Intern {
            get {
                return ResourceManager.GetString("EmploymentType_Intern", resourceCulture);
            }
        }

        public static string EmploymentStatus {
            get {
                return ResourceManager.GetString("EmploymentStatus", resourceCulture);
            }
        }

        public static string EmploymentStatus_Official {
            get {
                return ResourceManager.GetString("EmploymentStatus_Official", resourceCulture);
            }
        }

        public static string EmploymentStatus_Probation {
            get {
                return ResourceManager.GetString("EmploymentStatus_Probation", resourceCulture);
            }
        }

        public static string EmploymentStatus_OnLeave {
            get {
                return ResourceManager.GetString("EmploymentStatus_OnLeave", resourceCulture);
            }
        }

        public static string EmploymentStatus_Resigned {
            get {
                return ResourceManager.GetString("EmploymentStatus_Resigned", resourceCulture);
            }
        }

        public static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }

        public static string BaseSalary {
            get {
                return ResourceManager.GetString("BaseSalary", resourceCulture);
            }
        }

        public static string AnnualLeaveBalance {
            get {
                return ResourceManager.GetString("AnnualLeaveBalance", resourceCulture);
            }
        }

        public static string CitizenId {
            get {
                return ResourceManager.GetString("CitizenId", resourceCulture);
            }
        }

        public static string ResignDate {
            get {
                return ResourceManager.GetString("ResignDate", resourceCulture);
            }
        }

        public static string ResignReason {
            get {
                return ResourceManager.GetString("ResignReason", resourceCulture);
            }
        }
    }
}
