//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Models {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shift {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shift() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Models.Shift", typeof(Shift).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ShiftCode {
            get {
                return ResourceManager.GetString("ShiftCode", resourceCulture);
            }
        }
        
        public static string ShiftName {
            get {
                return ResourceManager.GetString("ShiftName", resourceCulture);
            }
        }
        
        public static string ShiftName_S {
            get {
                return ResourceManager.GetString("ShiftName_S", resourceCulture);
            }
        }
        
        public static string ShiftName_C {
            get {
                return ResourceManager.GetString("ShiftName_C", resourceCulture);
            }
        }
        
        public static string ShiftName_G {
            get {
                return ResourceManager.GetString("ShiftName_G", resourceCulture);
            }
        }
        
        public static string ShiftName_HC {
            get {
                return ResourceManager.GetString("ShiftName_HC", resourceCulture);
            }
        }
        
        public static string ShiftType {
            get {
                return ResourceManager.GetString("ShiftType", resourceCulture);
            }
        }
        
        public static string ShiftType_Morning {
            get {
                return ResourceManager.GetString("ShiftType_Morning", resourceCulture);
            }
        }
        
        public static string ShiftType_Afternoon {
            get {
                return ResourceManager.GetString("ShiftType_Afternoon", resourceCulture);
            }
        }
        
        public static string ShiftType_Split {
            get {
                return ResourceManager.GetString("ShiftType_Split", resourceCulture);
            }
        }
        
        public static string ShiftType_FullDay {
            get {
                return ResourceManager.GetString("ShiftType_FullDay", resourceCulture);
            }
        }
        
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        public static string StartTime2 {
            get {
                return ResourceManager.GetString("StartTime2", resourceCulture);
            }
        }
        
        public static string EndTime2 {
            get {
                return ResourceManager.GetString("EndTime2", resourceCulture);
            }
        }
        
        public static string BreakMinutes {
            get {
                return ResourceManager.GetString("BreakMinutes", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string TimeDisplay {
            get {
                return ResourceManager.GetString("TimeDisplay", resourceCulture);
            }
        }
    }
}
