//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Acc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Acc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Shared.Acc", typeof(Acc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create - Account.
        /// </summary>
        public static string Create_PageHeader {
            get {
                return ResourceManager.GetString("Create_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create - Account.
        /// </summary>
        public static string Create_PageTitle {
            get {
                return ResourceManager.GetString("Create_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete - Account.
        /// </summary>
        public static string Delete_PageHeader {
            get {
                return ResourceManager.GetString("Delete_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete - Account.
        /// </summary>
        public static string Delete_PageTitle {
            get {
                return ResourceManager.GetString("Delete_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is invalid..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        public static string Index_PageHeader {
            get {
                return ResourceManager.GetString("Index_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string Placeholder_Email {
            get {
                return ResourceManager.GetString("Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter fullname.
        /// </summary>
        public static string Placeholder_FullName {
            get {
                return ResourceManager.GetString("Placeholder_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username or email to search.
        /// </summary>
        public static string Placeholder_Search {
            get {
                return ResourceManager.GetString("Placeholder_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username.
        /// </summary>
        public static string Placeholder_Username {
            get {
                return ResourceManager.GetString("Placeholder_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update - Account.
        /// </summary>
        public static string Update_PageHeader {
            get {
                return ResourceManager.GetString("Update_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update - Account.
        /// </summary>
        public static string Update_PageTitle {
            get {
                return ResourceManager.GetString("Update_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a system account and automatically generate an employee profile if the role is store-based.
        /// </summary>
        public static string Create_SubTitle {
            get {
                return ResourceManager.GetString("Create_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Personal Information &amp; Account.
        /// </summary>
        public static string Create_Section_AccountInfo {
            get {
                return ResourceManager.GetString("Create_Section_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Employee Profile &amp; Store Assignment.
        /// </summary>
        public static string Create_Section_StoreInfo {
            get {
                return ResourceManager.GetString("Create_Section_StoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store-role accounts will automatically create an employee profile in the branch staff list.
        /// </summary>
        public static string Create_StoreInfoHint {
            get {
                return ResourceManager.GetString("Create_StoreInfoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-suggested from full name, can be customized.
        /// </summary>
        public static string Create_UsernameHint {
            get {
                return ResourceManager.GetString("Create_UsernameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Account Password.
        /// </summary>
        public static string Modal_QuickResetTitle {
            get {
                return ResourceManager.GetString("Modal_QuickResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting password for:.
        /// </summary>
        public static string Modal_QuickResetFor {
            get {
                return ResourceManager.GetString("Modal_QuickResetFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Modal_QuickResetNewPass {
            get {
                return ResourceManager.GetString("Modal_QuickResetNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Modal_QuickResetConfirmPass {
            get {
                return ResourceManager.GetString("Modal_QuickResetConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save New Password.
        /// </summary>
        public static string Modal_QuickResetSaveBtn {
            get {
                return ResourceManager.GetString("Modal_QuickResetSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage system accounts and add new staff for store branches.
        /// </summary>
        public static string Index_SubTitle {
            get {
                return ResourceManager.GetString("Index_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created successfully!.
        /// </summary>
        public static string Notice_CreatedSuccess {
            get {
                return ResourceManager.GetString("Notice_CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random secure password.
        /// </summary>
        public static string Create_GeneratePassHint {
            get {
                return ResourceManager.GetString("Create_GeneratePassHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Button_GenerateRandom {
            get {
                return ResourceManager.GetString("Button_GenerateRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password copied to clipboard!.
        /// </summary>
        public static string Toast_CopiedPassword {
            get {
                return ResourceManager.GetString("Toast_CopiedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter new password....
        /// </summary>
        public static string Modal_QuickResetPlaceholderConfirmPass {
            get {
                return ResourceManager.GetString("Modal_QuickResetPlaceholderConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click "Copy" to easily share credentials with the employee via Zalo/Email..
        /// </summary>
        public static string Modal_QuickResetHint {
            get {
                return ResourceManager.GetString("Modal_QuickResetHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account &amp; password copied to clipboard!.
        /// </summary>
        public static string Toast_CopiedAccountPassword {
            get {
                return ResourceManager.GetString("Toast_CopiedAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be at least 6 characters!.
        /// </summary>
        public static string Err_MinLengthPassword {
            get {
                return ResourceManager.GetString("Err_MinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation does not match!.
        /// </summary>
        public static string Err_PasswordMismatch {
            get {
                return ResourceManager.GetString("Err_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully!.
        /// </summary>
        public static string Toast_ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("Toast_ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Label_Account {
            get {
                return ResourceManager.GetString("Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }

        public static string Excel_Action => ResourceManager.GetString("Excel_Action", resourceCulture);
        public static string Excel_DownloadTemplate => ResourceManager.GetString("Excel_DownloadTemplate", resourceCulture);
        public static string Excel_Import => ResourceManager.GetString("Excel_Import", resourceCulture);
        public static string Excel_ImportTitle => ResourceManager.GetString("Excel_ImportTitle", resourceCulture);
        public static string Excel_SelectFile => ResourceManager.GetString("Excel_SelectFile", resourceCulture);
        public static string Excel_UploadAndImport => ResourceManager.GetString("Excel_UploadAndImport", resourceCulture);
        public static string Excel_TemplateNote => ResourceManager.GetString("Excel_TemplateNote", resourceCulture);
        public static string Excel_Close => ResourceManager.GetString("Excel_Close", resourceCulture);
        public static string Excel_Btn_Preview => ResourceManager.GetString("Excel_Btn_Preview", resourceCulture);
        public static string Excel_Btn_Back => ResourceManager.GetString("Excel_Btn_Back", resourceCulture);
        public static string Excel_Btn_Confirm => ResourceManager.GetString("Excel_Btn_Confirm", resourceCulture);
        public static string Excel_Summary_Total => ResourceManager.GetString("Excel_Summary_Total", resourceCulture);
        public static string Excel_Summary_Valid => ResourceManager.GetString("Excel_Summary_Valid", resourceCulture);
        public static string Excel_Summary_Invalid => ResourceManager.GetString("Excel_Summary_Invalid", resourceCulture);
        public static string Excel_Status_Valid => ResourceManager.GetString("Excel_Status_Valid", resourceCulture);
        public static string Excel_Col_Row => ResourceManager.GetString("Excel_Col_Row", resourceCulture);
        public static string Excel_Col_Status => ResourceManager.GetString("Excel_Col_Status", resourceCulture);
        public static string Excel_Col_Username => ResourceManager.GetString("Excel_Col_Username", resourceCulture);
        public static string Excel_Col_FullName => ResourceManager.GetString("Excel_Col_FullName", resourceCulture);
        public static string Excel_Col_Role => ResourceManager.GetString("Excel_Col_Role", resourceCulture);
        public static string Excel_Col_Store => ResourceManager.GetString("Excel_Col_Store", resourceCulture);
        public static string Excel_Col_EmpCode => ResourceManager.GetString("Excel_Col_EmpCode", resourceCulture);
        public static string Excel_Col_Errors => ResourceManager.GetString("Excel_Col_Errors", resourceCulture);
        public static string Excel_Status_Invalid => ResourceManager.GetString("Excel_Status_Invalid", resourceCulture);
        public static string Excel_Preview_Warning_HasErrors => ResourceManager.GetString("Excel_Preview_Warning_HasErrors", resourceCulture);
        public static string Excel_Preview_All_Valid => ResourceManager.GetString("Excel_Preview_All_Valid", resourceCulture);
        public static string Excel_Preview_No_Valid => ResourceManager.GetString("Excel_Preview_No_Valid", resourceCulture);
        public static string Excel_Btn_Verifying => ResourceManager.GetString("Excel_Btn_Verifying", resourceCulture);
        public static string Excel_Btn_Saving => ResourceManager.GetString("Excel_Btn_Saving", resourceCulture);
        public static string Excel_Step1_Note => ResourceManager.GetString("Excel_Step1_Note", resourceCulture);

        public static string Profile_PageTitle => ResourceManager.GetString("Profile_PageTitle", resourceCulture);
        public static string Profile_PageSubTitle => ResourceManager.GetString("Profile_PageSubTitle", resourceCulture);
        public static string Profile_ChangePassword => ResourceManager.GetString("Profile_ChangePassword", resourceCulture);
        public static string Profile_Back => ResourceManager.GetString("Profile_Back", resourceCulture);
        public static string Profile_Section_JobInfo => ResourceManager.GetString("Profile_Section_JobInfo", resourceCulture);
        public static string Profile_Store => ResourceManager.GetString("Profile_Store", resourceCulture);
        public static string Profile_StoreUnassigned => ResourceManager.GetString("Profile_StoreUnassigned", resourceCulture);
        public static string Profile_Role => ResourceManager.GetString("Profile_Role", resourceCulture);
        public static string Profile_EmploymentType => ResourceManager.GetString("Profile_EmploymentType", resourceCulture);
        public static string Profile_FullTime => ResourceManager.GetString("Profile_FullTime", resourceCulture);
        public static string Profile_PartTime => ResourceManager.GetString("Profile_PartTime", resourceCulture);
        public static string Profile_HourlyRate => ResourceManager.GetString("Profile_HourlyRate", resourceCulture);
        public static string Profile_BaseSalary => ResourceManager.GetString("Profile_BaseSalary", resourceCulture);
        public static string Profile_LeaveBalance => ResourceManager.GetString("Profile_LeaveBalance", resourceCulture);
        public static string Profile_Days => ResourceManager.GetString("Profile_Days", resourceCulture);
        public static string Profile_Section_PersonalInfo => ResourceManager.GetString("Profile_Section_PersonalInfo", resourceCulture);
        public static string Profile_CitizenId => ResourceManager.GetString("Profile_CitizenId", resourceCulture);
        public static string Profile_NotUpdated => ResourceManager.GetString("Profile_NotUpdated", resourceCulture);
        public static string Profile_DateOfBirth => ResourceManager.GetString("Profile_DateOfBirth", resourceCulture);
        public static string Profile_Gender => ResourceManager.GetString("Profile_Gender", resourceCulture);
        public static string Profile_Phone => ResourceManager.GetString("Profile_Phone", resourceCulture);
        public static string Profile_Email => ResourceManager.GetString("Profile_Email", resourceCulture);
        public static string Profile_JoinDate => ResourceManager.GetString("Profile_JoinDate", resourceCulture);
        public static string Profile_Section_SystemInfo => ResourceManager.GetString("Profile_Section_SystemInfo", resourceCulture);
        public static string Profile_AccountStatus => ResourceManager.GetString("Profile_AccountStatus", resourceCulture);
        public static string Profile_StatusActive => ResourceManager.GetString("Profile_StatusActive", resourceCulture);
        public static string Profile_StatusLocked => ResourceManager.GetString("Profile_StatusLocked", resourceCulture);
        public static string Profile_LastLogin => ResourceManager.GetString("Profile_LastLogin", resourceCulture);
        public static string Profile_NoData => ResourceManager.GetString("Profile_NoData", resourceCulture);
        public static string Profile_CreatedDate => ResourceManager.GetString("Profile_CreatedDate", resourceCulture);
    }
}
