//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Employee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Employee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Shared.Employee", typeof(Employee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create employee.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete employee.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create-Employee.
        /// </summary>
        public static string Create_PageHeader {
            get {
                return ResourceManager.GetString("Create_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create-Employee.
        /// </summary>
        public static string Create_PageTitle {
            get {
                return ResourceManager.GetString("Create_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this employee from the system? This action cannot be undone.
        /// </summary>
        public static string Delete_Confirm {
            get {
                return ResourceManager.GetString("Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete-Employee.
        /// </summary>
        public static string Delete_PageHeader {
            get {
                return ResourceManager.GetString("Delete_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete-Employee.
        /// </summary>
        public static string Delete_PageTitle {
            get {
                return ResourceManager.GetString("Delete_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit-Employee.
        /// </summary>
        public static string Edit_PageHeader {
            get {
                return ResourceManager.GetString("Edit_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit-Employee.
        /// </summary>
        public static string Edit_PageTitle {
            get {
                return ResourceManager.GetString("Edit_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Management.
        /// </summary>
        public static string Index_PageHeader {
            get {
                return ResourceManager.GetString("Index_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Management.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter employee Id.
        /// </summary>
        public static string PlaceHolder_EmployeeCode {
            get {
                return ResourceManager.GetString("PlaceHolder_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Employee ID, Full Name, Account ....
        /// </summary>
        public static string Placeholder_Search {
            get {
                return ResourceManager.GetString("Placeholder_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select store ---.
        /// </summary>
        public static string Placeholder_Store {
            get {
                return ResourceManager.GetString("Placeholder_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Active.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status all.
        /// </summary>
        public static string Status_All {
            get {
                return ResourceManager.GetString("Status_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Inactive.
        /// </summary>
        public static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
