//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Employee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Employee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Shared.Employee", typeof(Employee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create employee.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete employee.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create-Employee.
        /// </summary>
        public static string Create_PageHeader {
            get {
                return ResourceManager.GetString("Create_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create-Employee.
        /// </summary>
        public static string Create_PageTitle {
            get {
                return ResourceManager.GetString("Create_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this employee from the system? This action cannot be undone.
        /// </summary>
        public static string Delete_Confirm {
            get {
                return ResourceManager.GetString("Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete-Employee.
        /// </summary>
        public static string Delete_PageHeader {
            get {
                return ResourceManager.GetString("Delete_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete-Employee.
        /// </summary>
        public static string Delete_PageTitle {
            get {
                return ResourceManager.GetString("Delete_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit-Employee.
        /// </summary>
        public static string Edit_PageHeader {
            get {
                return ResourceManager.GetString("Edit_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit-Employee.
        /// </summary>
        public static string Edit_PageTitle {
            get {
                return ResourceManager.GetString("Edit_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Management.
        /// </summary>
        public static string Index_PageHeader {
            get {
                return ResourceManager.GetString("Index_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Management.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter employee Id.
        /// </summary>
        public static string PlaceHolder_EmployeeCode {
            get {
                return ResourceManager.GetString("PlaceHolder_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Employee ID, Full Name, Account ....
        /// </summary>
        public static string Placeholder_Search {
            get {
                return ResourceManager.GetString("Placeholder_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select store ---.
        /// </summary>
        public static string Placeholder_Store {
            get {
                return ResourceManager.GetString("Placeholder_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Active.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status all.
        /// </summary>
        public static string Status_All {
            get {
                return ResourceManager.GetString("Status_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Inactive.
        /// </summary>
        public static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employees found matching the filter.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete Employee Record.
        /// </summary>
        public static string Modal_DeleteTitle {
            get {
                return ResourceManager.GetString("Modal_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to permanently delete the employee record:.
        /// </summary>
        public static string Modal_DeleteWarning {
            get {
                return ResourceManager.GetString("Modal_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone. If you only want to suspend, use the status toggle instead.
        /// </summary>
        public static string Modal_DeleteCannotUndo {
            get {
                return ResourceManager.GetString("Modal_DeleteCannotUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string Modal_DeleteConfirmBtn {
            get {
                return ResourceManager.GetString("Modal_DeleteConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of employees assigned to store branches (Add new staff in Account Management).
        /// </summary>
        public static string Index_SubTitle {
            get {
                return ResourceManager.GetString("Index_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Code.
        /// </summary>
        public static string Column_EmployeeCode {
            get {
                return ResourceManager.GetString("Column_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Column_Store {
            get {
                return ResourceManager.GetString("Column_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Column_JoinDate {
            get {
                return ResourceManager.GetString("Column_JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Information &amp; Store.
        /// </summary>
        public static string Edit_SectionTitle {
            get {
                return ResourceManager.GetString("Edit_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently working (Active).
        /// </summary>
        public static string Edit_ActiveLabel {
            get {
                return ResourceManager.GetString("Edit_ActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update branch and working date information for the employee.
        /// </summary>
        public static string Edit_SubTitle {
            get {
                return ResourceManager.GetString("Edit_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee / Full Name.
        /// </summary>
        public static string Th_EmployeeName {
            get {
                return ResourceManager.GetString("Th_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID / Account.
        /// </summary>
        public static string Th_EmployeeIdAccount {
            get {
                return ResourceManager.GetString("Th_EmployeeIdAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email.
        /// </summary>
        public static string NoEmail {
            get {
                return ResourceManager.GetString("NoEmail", resourceCulture);
            }
        }

        public static string Create_SubTitle {
            get { return ResourceManager.GetString("Create_SubTitle", resourceCulture); }
        }
        public static string ExportExcel {
            get { return ResourceManager.GetString("ExportExcel", resourceCulture); }
        }
        public static string Stat_TotalEmployees {
            get { return ResourceManager.GetString("Stat_TotalEmployees", resourceCulture); }
        }
        public static string Stat_Active {
            get { return ResourceManager.GetString("Stat_Active", resourceCulture); }
        }
        public static string Stat_FullTime {
            get { return ResourceManager.GetString("Stat_FullTime", resourceCulture); }
        }
        public static string Stat_PartTime {
            get { return ResourceManager.GetString("Stat_PartTime", resourceCulture); }
        }
        public static string Stat_Probation {
            get { return ResourceManager.GetString("Stat_Probation", resourceCulture); }
        }
        public static string Modal_ResignTitle {
            get { return ResourceManager.GetString("Modal_ResignTitle", resourceCulture); }
        }
        public static string Modal_ResignNotice {
            get { return ResourceManager.GetString("Modal_ResignNotice", resourceCulture); }
        }
        public static string Button_Resign {
            get { return ResourceManager.GetString("Button_Resign", resourceCulture); }
        }
        public static string Resign_Success {
            get { return ResourceManager.GetString("Resign_Success", resourceCulture); }
        }
        public static string Section_PersonalInfo {
            get { return ResourceManager.GetString("Section_PersonalInfo", resourceCulture); }
        }
        public static string Section_JobInfo {
            get { return ResourceManager.GetString("Section_JobInfo", resourceCulture); }
        }
        public static string Section_Compensation {
            get { return ResourceManager.GetString("Section_Compensation", resourceCulture); }
        }
        public static string Badge_FullTime {
            get { return ResourceManager.GetString("Badge_FullTime", resourceCulture); }
        }
        public static string Badge_PartTime {
            get { return ResourceManager.GetString("Badge_PartTime", resourceCulture); }
        }
        public static string Badge_Intern {
            get { return ResourceManager.GetString("Badge_Intern", resourceCulture); }
        }
        public static string Badge_Resigned {
            get { return ResourceManager.GetString("Badge_Resigned", resourceCulture); }
        }
        public static string Badge_Probation {
            get { return ResourceManager.GetString("Badge_Probation", resourceCulture); }
        }
        public static string Excel_Action => ResourceManager.GetString("Excel_Action", resourceCulture);
        public static string Excel_DownloadTemplate => ResourceManager.GetString("Excel_DownloadTemplate", resourceCulture);
        public static string Excel_Import => ResourceManager.GetString("Excel_Import", resourceCulture);
        public static string Excel_ImportTitle => ResourceManager.GetString("Excel_ImportTitle", resourceCulture);
        public static string Excel_SelectFile => ResourceManager.GetString("Excel_SelectFile", resourceCulture);
        public static string Excel_UploadAndImport => ResourceManager.GetString("Excel_UploadAndImport", resourceCulture);
        public static string Excel_TemplateNote => ResourceManager.GetString("Excel_TemplateNote", resourceCulture);
        public static string Excel_Close => ResourceManager.GetString("Excel_Close", resourceCulture);
        public static string Excel_Btn_Preview => ResourceManager.GetString("Excel_Btn_Preview", resourceCulture);
        public static string Excel_Btn_Back => ResourceManager.GetString("Excel_Btn_Back", resourceCulture);
        public static string Excel_Btn_Confirm => ResourceManager.GetString("Excel_Btn_Confirm", resourceCulture);
        public static string Excel_Summary_Total => ResourceManager.GetString("Excel_Summary_Total", resourceCulture);
        public static string Excel_Summary_Valid => ResourceManager.GetString("Excel_Summary_Valid", resourceCulture);
        public static string Excel_Summary_Invalid => ResourceManager.GetString("Excel_Summary_Invalid", resourceCulture);
        public static string Excel_Status_Valid => ResourceManager.GetString("Excel_Status_Valid", resourceCulture);
        public static string Excel_Col_Row => ResourceManager.GetString("Excel_Col_Row", resourceCulture);
        public static string Excel_Col_Status => ResourceManager.GetString("Excel_Col_Status", resourceCulture);
        public static string Excel_Col_Username => ResourceManager.GetString("Excel_Col_Username", resourceCulture);
        public static string Excel_Col_FullName => ResourceManager.GetString("Excel_Col_FullName", resourceCulture);
        public static string Excel_Col_Role => ResourceManager.GetString("Excel_Col_Role", resourceCulture);
        public static string Excel_Col_Store => ResourceManager.GetString("Excel_Col_Store", resourceCulture);
        public static string Excel_Col_EmpCode => ResourceManager.GetString("Excel_Col_EmpCode", resourceCulture);
        public static string Excel_Col_Errors => ResourceManager.GetString("Excel_Col_Errors", resourceCulture);
        public static string Excel_Status_Invalid => ResourceManager.GetString("Excel_Status_Invalid", resourceCulture);
        public static string Excel_Preview_Warning_HasErrors => ResourceManager.GetString("Excel_Preview_Warning_HasErrors", resourceCulture);
        public static string Excel_Preview_All_Valid => ResourceManager.GetString("Excel_Preview_All_Valid", resourceCulture);
        public static string Excel_Preview_No_Valid => ResourceManager.GetString("Excel_Preview_No_Valid", resourceCulture);
        public static string Excel_Btn_Verifying => ResourceManager.GetString("Excel_Btn_Verifying", resourceCulture);
        public static string Excel_Btn_Saving => ResourceManager.GetString("Excel_Btn_Saving", resourceCulture);
        public static string Excel_Step1_Note => ResourceManager.GetString("Excel_Step1_Note", resourceCulture);
    }
}