using System;
using System.IO;
using System.Text.RegularExpressions;
using System.Text;

var resxFile = "RequestResource.resx";
var designerFile = "RequestResource.Designer.cs";

var resxContent = File.ReadAllText(resxFile);
var matches = Regex.Matches(resxContent, @"<data name=""([^""]+)""");

var sb = new StringBuilder();
sb.AppendLine(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Shared {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""System.Resources.Tools.StronglyTypedResourceBuilder"", ""18.0.0.0"")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(""Microsoft.Performance"", ""CA1811:AvoidUncalledPrivateCode"")]
        internal RequestResource() { }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(""RWPM.Resources.Shared.RequestResource"", typeof(RequestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }");

foreach (Match m in matches)
{
    var key = m.Groups[1].Value;
    sb.AppendLine();
    sb.AppendLine($@"        public static string {key} {{");
    sb.AppendLine($@"            get {{");
    sb.AppendLine($@"                return ResourceManager.GetString(""{key}"", resourceCulture);");
    sb.AppendLine($@"            }}");
    sb.AppendLine($@"        }}");
}

sb.AppendLine("    }");
sb.AppendLine("}");

File.WriteAllText(designerFile, sb.ToString());
Console.WriteLine("Done generating Designer file.");
