//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NavigationBarResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavigationBarResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Shared.NavigationBarResource", typeof(NavigationBarResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account management.
        /// </summary>
        public static string AccountManagement {
            get {
                return ResourceManager.GetString("AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account profile.
        /// </summary>
        public static string AccountProfile {
            get {
                return ResourceManager.GetString("AccountProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories management.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Off.
        /// </summary>
        public static string DayOff {
            get {
                return ResourceManager.GetString("DayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared data.
        /// </summary>
        public static string DeclaredData {
            get {
                return ResourceManager.GetString("DeclaredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Management.
        /// </summary>
        public static string EmployeeManagement {
            get {
                return ResourceManager.GetString("EmployeeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo Management.
        /// </summary>
        public static string LotNoManagement {
            get {
                return ResourceManager.GetString("LotNoManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other functions.
        /// </summary>
        public static string OrtherFunctions {
            get {
                return ResourceManager.GetString("OrtherFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store List.
        /// </summary>
        public static string StoreList {
            get {
                return ResourceManager.GetString("StoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire.
        /// </summary>
        public static string Wire {
            get {
                return ResourceManager.GetString("Wire", resourceCulture);
            }
        }
    }
}
