//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Shared.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin accounts do not need to check in..
        /// </summary>
        public static string Attendance_AdminNoNeed {
            get {
                return ResourceManager.GetString("Attendance_AdminNoNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Employees.
        /// </summary>
        public static string Attendance_AllEmployees {
            get {
                return ResourceManager.GetString("Attendance_AllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance History.
        /// </summary>
        public static string Attendance_AllHistory {
            get {
                return ResourceManager.GetString("Attendance_AllHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already checked in today..
        /// </summary>
        public static string Attendance_AlreadyCheckedIn {
            get {
                return ResourceManager.GetString("Attendance_AlreadyCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already checked out today..
        /// </summary>
        public static string Attendance_AlreadyCheckedOut {
            get {
                return ResourceManager.GetString("Attendance_AlreadyCheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK IN.
        /// </summary>
        public static string Attendance_BtnCheckIn {
            get {
                return ResourceManager.GetString("Attendance_BtnCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK OUT.
        /// </summary>
        public static string Attendance_BtnCheckOut {
            get {
                return ResourceManager.GetString("Attendance_BtnCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in Time.
        /// </summary>
        public static string Attendance_CheckInCol {
            get {
                return ResourceManager.GetString("Attendance_CheckInCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked in successfully!.
        /// </summary>
        public static string Attendance_CheckInSuccess {
            get {
                return ResourceManager.GetString("Attendance_CheckInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in time:.
        /// </summary>
        public static string Attendance_CheckInTime {
            get {
                return ResourceManager.GetString("Attendance_CheckInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out Time.
        /// </summary>
        public static string Attendance_CheckOutCol {
            get {
                return ResourceManager.GetString("Attendance_CheckOutCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked out successfully!.
        /// </summary>
        public static string Attendance_CheckOutSuccess {
            get {
                return ResourceManager.GetString("Attendance_CheckOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out time:.
        /// </summary>
        public static string Attendance_CheckOutTime {
            get {
                return ResourceManager.GetString("Attendance_CheckOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed today&apos;s attendance..
        /// </summary>
        public static string Attendance_Completed {
            get {
                return ResourceManager.GetString("Attendance_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Attendance_EmployeeCol {
            get {
                return ResourceManager.GetString("Attendance_EmployeeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List:.
        /// </summary>
        public static string Attendance_EmployeeList {
            get {
                return ResourceManager.GetString("Attendance_EmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Attendance History.
        /// </summary>
        public static string Attendance_MyHistory {
            get {
                return ResourceManager.GetString("Attendance_MyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attendance data available..
        /// </summary>
        public static string Attendance_NoData {
            get {
                return ResourceManager.GetString("Attendance_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t checked in today..
        /// </summary>
        public static string Attendance_NotCheckedIn {
            get {
                return ResourceManager.GetString("Attendance_NotCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search username....
        /// </summary>
        public static string Attendance_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Attendance_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shift.
        /// </summary>
        public static string Attendance_SelectShift {
            get {
                return ResourceManager.GetString("Attendance_SelectShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance &amp; History.
        /// </summary>
        public static string Attendance_Title {
            get {
                return ResourceManager.GetString("Attendance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Attendance.
        /// </summary>
        public static string Attendance_Today {
            get {
                return ResourceManager.GetString("Attendance_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are more than 30 minutes late and cannot check-in for this shift!.
        /// </summary>
        public static string Attendance_TooLate {
            get {
                return ResourceManager.GetString("Attendance_TooLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Button_Action {
            get {
                return ResourceManager.GetString("Button_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Data.
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse File.
        /// </summary>
        public static string Button_BrowseFile {
            get {
                return ResourceManager.GetString("Button_BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Button_ChangePassword {
            get {
                return ResourceManager.GetString("Button_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export excel.
        /// </summary>
        public static string Button_ExportExcel {
            get {
                return ResourceManager.GetString("Button_ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Button_GoBack {
            get {
                return ResourceManager.GetString("Button_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import excel.
        /// </summary>
        public static string Button_ImportExcel {
            get {
                return ResourceManager.GetString("Button_ImportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Button_Info {
            get {
                return ResourceManager.GetString("Button_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Button_Reset {
            get {
                return ResourceManager.GetString("Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Button_SaveChanges {
            get {
                return ResourceManager.GetString("Button_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Button_View {
            get {
                return ResourceManager.GetString("Button_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this data?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data will be deleted.
        /// </summary>
        public static string DataWillBeDeleted {
            get {
                return ResourceManager.GetString("DataWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download attached file.
        /// </summary>
        public static string DownloadAttachedFile {
            get {
                return ResourceManager.GetString("DownloadAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download template file.
        /// </summary>
        public static string DownloadTemplateFile {
            get {
                return ResourceManager.GetString("DownloadTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; drop your file here or.
        /// </summary>
        public static string DragOrDropFile {
            get {
                return ResourceManager.GetString("DragOrDropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select account ---.
        /// </summary>
        public static string Dropdown_SelectAccount {
            get {
                return ResourceManager.GetString("Dropdown_SelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select department ---.
        /// </summary>
        public static string Dropdown_SelectDepartment {
            get {
                return ResourceManager.GetString("Dropdown_SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select document processing flow ---.
        /// </summary>
        public static string Dropdown_SelectDocFlow {
            get {
                return ResourceManager.GetString("Dropdown_SelectDocFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select document group ---.
        /// </summary>
        public static string Dropdown_SelectDocGrpCat {
            get {
                return ResourceManager.GetString("Dropdown_SelectDocGrpCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select document type ---.
        /// </summary>
        public static string Dropdown_SelectDocTypeCat {
            get {
                return ResourceManager.GetString("Dropdown_SelectDocTypeCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select factory ---.
        /// </summary>
        public static string Dropdown_SelectFactory {
            get {
                return ResourceManager.GetString("Dropdown_SelectFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select store ---.
        /// </summary>
        public static string Dropdown_SelectStore {
            get {
                return ResourceManager.GetString("Dropdown_SelectStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select year ---.
        /// </summary>
        public static string DropDown_SelectYear {
            get {
                return ResourceManager.GetString("DropDown_SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has an invalid value..
        /// </summary>
        public static string EnumInvalid {
            get {
                return ResourceManager.GetString("EnumInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init data.
        /// </summary>
        public static string InitData {
            get {
                return ResourceManager.GetString("InitData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init data success..
        /// </summary>
        public static string InitDataSuccess {
            get {
                return ResourceManager.GetString("InitDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or drag-and-drop an Excel file.
        /// </summary>
        public static string Label_SelectFileExcel {
            get {
                return ResourceManager.GetString("Label_SelectFileExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 2 days.
        /// </summary>
        public static string Last2Days {
            get {
                return ResourceManager.GetString("Last2Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days.
        /// </summary>
        public static string Last30Days {
            get {
                return ResourceManager.GetString("Last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading. Please wait..
        /// </summary>
        public static string LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be more than {1} characters..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} characters long..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file attached.
        /// </summary>
        public static string NoFileAttached {
            get {
                return ResourceManager.GetString("NoFileAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created successfully!.
        /// </summary>
        public static string Notification_CreatedSuccessfully {
            get {
                return ResourceManager.GetString("Notification_CreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully!.
        /// </summary>
        public static string Notification_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("Notification_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited successfully!.
        /// </summary>
        public static string Notification_EditedSuccessfully {
            get {
                return ResourceManager.GetString("Notification_EditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ObjectStatus {
            get {
                return ResourceManager.GetString("ObjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Display all ---.
        /// </summary>
        public static string ObjectStatus_Default {
            get {
                return ResourceManager.GetString("ObjectStatus_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ObjectStatus_IsActive {
            get {
                return ResourceManager.GetString("ObjectStatus_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string ObjectStatus_IsInactive {
            get {
                return ResourceManager.GetString("ObjectStatus_IsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must start with a letter and contain only letters and digits..
        /// </summary>
        public static string RegularExpression_AlphabetAndDigitRegex {
            get {
                return ResourceManager.GetString("RegularExpression_AlphabetAndDigitRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contain only letters, digits, underscores (_), or dashes (-)..
        /// </summary>
        public static string RegularExpression_CodeRegex {
            get {
                return ResourceManager.GetString("RegularExpression_CodeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least 8 characters long, including at least 1 uppercase letter, 1 lowercase letter, and 1 number..
        /// </summary>
        public static string RegularExpression_PasswordRegex {
            get {
                return ResourceManager.GetString("RegularExpression_PasswordRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must start with a letter and contain only letters, digits, underscores (_) or dashes (-)..
        /// </summary>
        public static string RegularExpression_UsernameRegex {
            get {
                return ResourceManager.GetString("RegularExpression_UsernameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one value..
        /// </summary>
        public static string RequiredIntegerSelection {
            get {
                return ResourceManager.GetString("RequiredIntegerSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or drag-and-drop an Excel file.
        /// </summary>
        public static string SelectExcelFile {
            get {
                return ResourceManager.GetString("SelectExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0}–{1} of {2} records.
        /// </summary>
        public static string TotalRecordBar {
            get {
                return ResourceManager.GetString("TotalRecordBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by.
        /// </summary>
        public static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated date.
        /// </summary>
        public static string UpdatedDate {
            get {
                return ResourceManager.GetString("UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        public static string RegularExpression_DigitsOnly {
            get {
                return ResourceManager.GetString("RegularExpression_DigitsOnly", resourceCulture);
            }
        }
    }
}
