//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Shared {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shift {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shift() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Shared.Shift", typeof(Shift).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        public static string Index_PageHeader {
            get {
                return ResourceManager.GetString("Index_PageHeader", resourceCulture);
            }
        }
        
        public static string Create_PageTitle {
            get {
                return ResourceManager.GetString("Create_PageTitle", resourceCulture);
            }
        }
        
        public static string Create_PageHeader {
            get {
                return ResourceManager.GetString("Create_PageHeader", resourceCulture);
            }
        }
        
        public static string Edit_PageTitle {
            get {
                return ResourceManager.GetString("Edit_PageTitle", resourceCulture);
            }
        }
        
        public static string Edit_PageHeader {
            get {
                return ResourceManager.GetString("Edit_PageHeader", resourceCulture);
            }
        }
        
        public static string Placeholder_Search {
            get {
                return ResourceManager.GetString("Placeholder_Search", resourceCulture);
            }
        }
        
        public static string Placeholder_ShiftCode {
            get {
                return ResourceManager.GetString("Placeholder_ShiftCode", resourceCulture);
            }
        }
        
        public static string Placeholder_ShiftName {
            get {
                return ResourceManager.GetString("Placeholder_ShiftName", resourceCulture);
            }
        }
        
        public static string Placeholder_Description {
            get {
                return ResourceManager.GetString("Placeholder_Description", resourceCulture);
            }
        }
        
        public static string SplitShiftSection {
            get {
                return ResourceManager.GetString("SplitShiftSection", resourceCulture);
            }
        }
        
        public static string Delete_PageTitle {
            get {
                return ResourceManager.GetString("Delete_PageTitle", resourceCulture);
            }
        }
        
        public static string Delete_PageHeader {
            get {
                return ResourceManager.GetString("Delete_PageHeader", resourceCulture);
            }
        }
        
        public static string Delete_Warning {
            get {
                return ResourceManager.GetString("Delete_Warning", resourceCulture);
            }
        }
        
        public static string AttendancePolicy_Title {
            get {
                return ResourceManager.GetString("AttendancePolicy_Title", resourceCulture);
            }
        }
        
        public static string AttendancePolicy_Description {
            get {
                return ResourceManager.GetString("AttendancePolicy_Description", resourceCulture);
            }
        }
        
        public static string Placeholder_DefaultMinutes {
            get {
                return ResourceManager.GetString("Placeholder_DefaultMinutes", resourceCulture);
            }
        }
        
        public static string Badge_Template {
            get {
                return ResourceManager.GetString("Badge_Template", resourceCulture);
            }
        }
        
        public static string Badge_Custom {
            get {
                return ResourceManager.GetString("Badge_Custom", resourceCulture);
            }
        }
        
        public static string Filter_AllClassifications {
            get {
                return ResourceManager.GetString("Filter_AllClassifications", resourceCulture);
            }
        }
        
        public static string Shift_IsTemplate_Hint {
            get {
                return ResourceManager.GetString("Shift_IsTemplate_Hint", resourceCulture);
            }
        }
        
        public static string AttendancePolicy_UseDefault {
            get {
                return ResourceManager.GetString("AttendancePolicy_UseDefault", resourceCulture);
            }
        }
        
        public static string AttendancePolicy_InheritNotice {
            get {
                return ResourceManager.GetString("AttendancePolicy_InheritNotice", resourceCulture);
            }
        }
        
        public static string Scope_Title {
            get {
                return ResourceManager.GetString("Scope_Title", resourceCulture);
            }
        }
        
        public static string Scope_AllStores {
            get {
                return ResourceManager.GetString("Scope_AllStores", resourceCulture);
            }
        }
        
        public static string Filter_AllStores {
            get {
                return ResourceManager.GetString("Filter_AllStores", resourceCulture);
            }
        }
    }
}
