//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Shared {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Store {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Store() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Shared.Store", typeof(Store).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Create_PageHeader {
            get {
                return ResourceManager.GetString("Create_PageHeader", resourceCulture);
            }
        }
        
        public static string Create_PageTitle {
            get {
                return ResourceManager.GetString("Create_PageTitle", resourceCulture);
            }
        }
        
        public static string Delete_PageHeader {
            get {
                return ResourceManager.GetString("Delete_PageHeader", resourceCulture);
            }
        }
        
        public static string Delete_PageTitle {
            get {
                return ResourceManager.GetString("Delete_PageTitle", resourceCulture);
            }
        }
        
        public static string Delete_Warning {
            get {
                return ResourceManager.GetString("Delete_Warning", resourceCulture);
            }
        }
        
        public static string Edit_PageHeader {
            get {
                return ResourceManager.GetString("Edit_PageHeader", resourceCulture);
            }
        }
        
        public static string Edit_PageTitle {
            get {
                return ResourceManager.GetString("Edit_PageTitle", resourceCulture);
            }
        }
        
        public static string Index_PageHeader {
            get {
                return ResourceManager.GetString("Index_PageHeader", resourceCulture);
            }
        }
        
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        public static string Placeholder_Address {
            get {
                return ResourceManager.GetString("Placeholder_Address", resourceCulture);
            }
        }
        
        public static string Placeholder_Phone {
            get {
                return ResourceManager.GetString("Placeholder_Phone", resourceCulture);
            }
        }
        
        public static string Placeholder_Search {
            get {
                return ResourceManager.GetString("Placeholder_Search", resourceCulture);
            }
        }
        
        public static string Placeholder_StoreCode {
            get {
                return ResourceManager.GetString("Placeholder_StoreCode", resourceCulture);
            }
        }
        
        public static string Placeholder_StoreName {
            get {
                return ResourceManager.GetString("Placeholder_StoreName", resourceCulture);
            }
        }
        
        public static string StatusUpdateSuccess {
            get {
                return ResourceManager.GetString("StatusUpdateSuccess", resourceCulture);
            }
        }
        
        public static string StatusUpdateFailed {
            get {
                return ResourceManager.GetString("StatusUpdateFailed", resourceCulture);
            }
        }
        
        public static string Dropdown_SelectStore {
            get {
                return ResourceManager.GetString("Dropdown_SelectStore", resourceCulture);
            }
        }
        
        public static string GeoHeader {
            get {
                return ResourceManager.GetString("GeoHeader", resourceCulture);
            }
        }
        
        public static string Placeholder_MapSearch {
            get {
                return ResourceManager.GetString("Placeholder_MapSearch", resourceCulture);
            }
        }
        
        public static string Btn_SearchAddress {
            get {
                return ResourceManager.GetString("Btn_SearchAddress", resourceCulture);
            }
        }
        
        public static string Label_SuggestedLocations {
            get {
                return ResourceManager.GetString("Label_SuggestedLocations", resourceCulture);
            }
        }
        
        public static string Instruction_MapHelp {
            get {
                return ResourceManager.GetString("Instruction_MapHelp", resourceCulture);
            }
        }
        
        public static string Map_GoogleStreets {
            get {
                return ResourceManager.GetString("Map_GoogleStreets", resourceCulture);
            }
        }
        
        public static string Map_GoogleSatellite {
            get {
                return ResourceManager.GetString("Map_GoogleSatellite", resourceCulture);
            }
        }
        
        public static string Map_OSM {
            get {
                return ResourceManager.GetString("Map_OSM", resourceCulture);
            }
        }
        
        public static string Search_Searching {
            get {
                return ResourceManager.GetString("Search_Searching", resourceCulture);
            }
        }
        
        public static string Search_EmptyAlert {
            get {
                return ResourceManager.GetString("Search_EmptyAlert", resourceCulture);
            }
        }
        
        public static string Search_NotFoundAlert {
            get {
                return ResourceManager.GetString("Search_NotFoundAlert", resourceCulture);
            }
        }
        
        public static string Search_ErrorAlert {
            get {
                return ResourceManager.GetString("Search_ErrorAlert", resourceCulture);
            }
        }
    }
}
