//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWPM.Resources.Shared {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Store {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Store() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWPM.Resources.Shared.Store", typeof(Store).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Create_PageHeader {
            get {
                return ResourceManager.GetString("Create_PageHeader", resourceCulture);
            }
        }
        
        public static string Create_PageTitle {
            get {
                return ResourceManager.GetString("Create_PageTitle", resourceCulture);
            }
        }
        
        public static string Delete_PageHeader {
            get {
                return ResourceManager.GetString("Delete_PageHeader", resourceCulture);
            }
        }
        
        public static string Delete_PageTitle {
            get {
                return ResourceManager.GetString("Delete_PageTitle", resourceCulture);
            }
        }
        
        public static string Delete_Warning {
            get {
                return ResourceManager.GetString("Delete_Warning", resourceCulture);
            }
        }
        
        public static string Edit_PageHeader {
            get {
                return ResourceManager.GetString("Edit_PageHeader", resourceCulture);
            }
        }
        
        public static string Edit_PageTitle {
            get {
                return ResourceManager.GetString("Edit_PageTitle", resourceCulture);
            }
        }
        
        public static string Index_PageHeader {
            get {
                return ResourceManager.GetString("Index_PageHeader", resourceCulture);
            }
        }
        
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        public static string Placeholder_Address {
            get {
                return ResourceManager.GetString("Placeholder_Address", resourceCulture);
            }
        }
        
        public static string Placeholder_Phone {
            get {
                return ResourceManager.GetString("Placeholder_Phone", resourceCulture);
            }
        }
        
        public static string Placeholder_Search {
            get {
                return ResourceManager.GetString("Placeholder_Search", resourceCulture);
            }
        }
        
        public static string Placeholder_StoreCode {
            get {
                return ResourceManager.GetString("Placeholder_StoreCode", resourceCulture);
            }
        }
        
        public static string Placeholder_StoreName {
            get {
                return ResourceManager.GetString("Placeholder_StoreName", resourceCulture);
            }
        }
        
        public static string StatusUpdateSuccess {
            get {
                return ResourceManager.GetString("StatusUpdateSuccess", resourceCulture);
            }
        }
        
        public static string StatusUpdateFailed {
            get {
                return ResourceManager.GetString("StatusUpdateFailed", resourceCulture);
            }
        }
        
        public static string Dropdown_SelectStore {
            get {
                return ResourceManager.GetString("Dropdown_SelectStore", resourceCulture);
            }
        }
        
        public static string GeoHeader {
            get {
                return ResourceManager.GetString("GeoHeader", resourceCulture);
            }
        }
        
        public static string Placeholder_MapSearch {
            get {
                return ResourceManager.GetString("Placeholder_MapSearch", resourceCulture);
            }
        }
        
        public static string Btn_SearchAddress {
            get {
                return ResourceManager.GetString("Btn_SearchAddress", resourceCulture);
            }
        }
        
        public static string Label_SuggestedLocations {
            get {
                return ResourceManager.GetString("Label_SuggestedLocations", resourceCulture);
            }
        }
        
        public static string Instruction_MapHelp {
            get {
                return ResourceManager.GetString("Instruction_MapHelp", resourceCulture);
            }
        }
        
        public static string Map_GoogleStreets {
            get {
                return ResourceManager.GetString("Map_GoogleStreets", resourceCulture);
            }
        }
        
        public static string Map_GoogleSatellite {
            get {
                return ResourceManager.GetString("Map_GoogleSatellite", resourceCulture);
            }
        }
        
        public static string Map_OSM {
            get {
                return ResourceManager.GetString("Map_OSM", resourceCulture);
            }
        }
        
        public static string Search_Searching {
            get {
                return ResourceManager.GetString("Search_Searching", resourceCulture);
            }
        }
        
        public static string Search_EmptyAlert {
            get {
                return ResourceManager.GetString("Search_EmptyAlert", resourceCulture);
            }
        }
        
        public static string Search_NotFoundAlert {
            get {
                return ResourceManager.GetString("Search_NotFoundAlert", resourceCulture);
            }
        }
        
        public static string Search_ErrorAlert {
            get {
                return ResourceManager.GetString("Search_ErrorAlert", resourceCulture);
            }
        }
        
        public static string Table_GeoLocation {
            get {
                return ResourceManager.GetString("Table_GeoLocation", resourceCulture);
            }
        }
        
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        public static string NotLocated {
            get {
                return ResourceManager.GetString("NotLocated", resourceCulture);
            }
        }

        public static string ConfigHeader_Management {
            get {
                return ResourceManager.GetString("ConfigHeader_Management", resourceCulture);
            }
        }

        public static string Dropdown_SelectManager {
            get {
                return ResourceManager.GetString("Dropdown_SelectManager", resourceCulture);
            }
        }

        public static string Label_OpeningTimeExample {
            get {
                return ResourceManager.GetString("Label_OpeningTimeExample", resourceCulture);
            }
        }

        public static string Help_OpeningTime {
            get {
                return ResourceManager.GetString("Help_OpeningTime", resourceCulture);
            }
        }

        public static string Label_ClosingTimeExample {
            get {
                return ResourceManager.GetString("Label_ClosingTimeExample", resourceCulture);
            }
        }

        public static string Help_ClosingTime {
            get {
                return ResourceManager.GetString("Help_ClosingTime", resourceCulture);
            }
        }

        public static string Index_Subtitle {
            get {
                return ResourceManager.GetString("Index_Subtitle", resourceCulture);
            }
        }

        public static string Table_Manager {
            get {
                return ResourceManager.GetString("Table_Manager", resourceCulture);
            }
        }

        public static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }

        public static string Badge_NoGPS {
            get {
                return ResourceManager.GetString("Badge_NoGPS", resourceCulture);
            }
        }

        public static string Tooltip_ViewDetails {
            get {
                return ResourceManager.GetString("Tooltip_ViewDetails", resourceCulture);
            }
        }

        public static string Details_PageHeader {
            get {
                return ResourceManager.GetString("Details_PageHeader", resourceCulture);
            }
        }

        public static string Details_UnsetAddress {
            get {
                return ResourceManager.GetString("Details_UnsetAddress", resourceCulture);
            }
        }

        public static string KPI_Manager {
            get {
                return ResourceManager.GetString("KPI_Manager", resourceCulture);
            }
        }

        public static string KPI_TotalEmployees {
            get {
                return ResourceManager.GetString("KPI_TotalEmployees", resourceCulture);
            }
        }

        public static string Unit_People {
            get {
                return ResourceManager.GetString("Unit_People", resourceCulture);
            }
        }

        public static string KPI_TodayAttendance {
            get {
                return ResourceManager.GetString("KPI_TodayAttendance", resourceCulture);
            }
        }

        public static string Unit_Records {
            get {
                return ResourceManager.GetString("Unit_Records", resourceCulture);
            }
        }

        public static string KPI_OperatingHours {
            get {
                return ResourceManager.GetString("KPI_OperatingHours", resourceCulture);
            }
        }

        public static string AllDayOperating {
            get {
                return ResourceManager.GetString("AllDayOperating", resourceCulture);
            }
        }

        public static string Tab_InfoAndMap {
            get {
                return ResourceManager.GetString("Tab_InfoAndMap", resourceCulture);
            }
        }

        public static string Tab_Employees {
            get {
                return ResourceManager.GetString("Tab_Employees", resourceCulture);
            }
        }

        public static string Tab_Shifts {
            get {
                return ResourceManager.GetString("Tab_Shifts", resourceCulture);
            }
        }

        public static string Tab_TodayAttendance {
            get {
                return ResourceManager.GetString("Tab_TodayAttendance", resourceCulture);
            }
        }

        public static string Details_BranchConfig {
            get {
                return ResourceManager.GetString("Details_BranchConfig", resourceCulture);
            }
        }

        public static string Details_OpenTimeLabel {
            get {
                return ResourceManager.GetString("Details_OpenTimeLabel", resourceCulture);
            }
        }

        public static string Details_CloseTimeLabel {
            get {
                return ResourceManager.GetString("Details_CloseTimeLabel", resourceCulture);
            }
        }

        public static string Details_GPSRadius {
            get {
                return ResourceManager.GetString("Details_GPSRadius", resourceCulture);
            }
        }

        public static string Details_AllowedDistance {
            get {
                return ResourceManager.GetString("Details_AllowedDistance", resourceCulture);
            }
        }

        public static string Details_BranchStatus {
            get {
                return ResourceManager.GetString("Details_BranchStatus", resourceCulture);
            }
        }

        public static string Details_CreatedDate {
            get {
                return ResourceManager.GetString("Details_CreatedDate", resourceCulture);
            }
        }

        public static string Details_UpdatedDate {
            get {
                return ResourceManager.GetString("Details_UpdatedDate", resourceCulture);
            }
        }

        public static string Details_GPSMapHeader {
            get {
                return ResourceManager.GetString("Details_GPSMapHeader", resourceCulture);
            }
        }

        public static string Details_Coordinates {
            get {
                return ResourceManager.GetString("Details_Coordinates", resourceCulture);
            }
        }

        public static string Details_NoGPSAlert {
            get {
                return ResourceManager.GetString("Details_NoGPSAlert", resourceCulture);
            }
        }

        public static string EmpTable_Code {
            get {
                return ResourceManager.GetString("EmpTable_Code", resourceCulture);
            }
        }

        public static string EmpTable_FullName {
            get {
                return ResourceManager.GetString("EmpTable_FullName", resourceCulture);
            }
        }

        public static string EmpTable_Email {
            get {
                return ResourceManager.GetString("EmpTable_Email", resourceCulture);
            }
        }

        public static string EmpTable_Phone {
            get {
                return ResourceManager.GetString("EmpTable_Phone", resourceCulture);
            }
        }

        public static string EmpTable_ContractType {
            get {
                return ResourceManager.GetString("EmpTable_ContractType", resourceCulture);
            }
        }

        public static string EmpTable_Status {
            get {
                return ResourceManager.GetString("EmpTable_Status", resourceCulture);
            }
        }

        public static string EmpTable_Working {
            get {
                return ResourceManager.GetString("EmpTable_Working", resourceCulture);
            }
        }

        public static string EmpTable_Resigned {
            get {
                return ResourceManager.GetString("EmpTable_Resigned", resourceCulture);
            }
        }

        public static string EmpTable_Empty {
            get {
                return ResourceManager.GetString("EmpTable_Empty", resourceCulture);
            }
        }

        public static string ShiftTable_Code {
            get {
                return ResourceManager.GetString("ShiftTable_Code", resourceCulture);
            }
        }

        public static string ShiftTable_Name {
            get {
                return ResourceManager.GetString("ShiftTable_Name", resourceCulture);
            }
        }

        public static string ShiftTable_TimeFrame {
            get {
                return ResourceManager.GetString("ShiftTable_TimeFrame", resourceCulture);
            }
        }

        public static string ShiftTable_BreakMinutes {
            get {
                return ResourceManager.GetString("ShiftTable_BreakMinutes", resourceCulture);
            }
        }

        public static string ShiftTable_Scope {
            get {
                return ResourceManager.GetString("ShiftTable_Scope", resourceCulture);
            }
        }

        public static string Unit_Minutes {
            get {
                return ResourceManager.GetString("Unit_Minutes", resourceCulture);
            }
        }

        public static string ShiftScope_SystemTemplate {
            get {
                return ResourceManager.GetString("ShiftScope_SystemTemplate", resourceCulture);
            }
        }

        public static string ShiftScope_BranchSpecific {
            get {
                return ResourceManager.GetString("ShiftScope_BranchSpecific", resourceCulture);
            }
        }

        public static string ShiftTable_Empty {
            get {
                return ResourceManager.GetString("ShiftTable_Empty", resourceCulture);
            }
        }

        public static string AttTable_Account {
            get {
                return ResourceManager.GetString("AttTable_Account", resourceCulture);
            }
        }

        public static string AttTable_CheckIn {
            get {
                return ResourceManager.GetString("AttTable_CheckIn", resourceCulture);
            }
        }

        public static string AttTable_CheckOut {
            get {
                return ResourceManager.GetString("AttTable_CheckOut", resourceCulture);
            }
        }

        public static string AttTable_GPSDistance {
            get {
                return ResourceManager.GetString("AttTable_GPSDistance", resourceCulture);
            }
        }

        public static string AttTable_Status {
            get {
                return ResourceManager.GetString("AttTable_Status", resourceCulture);
            }
        }

        public static string AttStatus_Valid {
            get {
                return ResourceManager.GetString("AttStatus_Valid", resourceCulture);
            }
        }

        public static string AttTable_Empty {
            get {
                return ResourceManager.GetString("AttTable_Empty", resourceCulture);
            }
        }
    }
}
